Feature data migration redshift snowflake
KV-APAC-DNA/gitadfadbplt001 pull request #10
Opened 2023-12-04 06:38 UTC by nbanga01

Feature: Historical ADF Pipeline for Redshift to Snowflake

## Description & motivation
Initial Commit from feature to main branch.

## To-do before merge
Wait till 5th Dec Data load, to do merge

## Screenshots:
NA

## Validation of ADF Artifacts:
- Data from Redshift to move in Snowflake.
- Check Metadata log tables for more status.

## Changes to existing ADF Artifacts:
No changes. It is a new development.

## Checklist:

- [x] I confirmed and have no doubts that there are no confidential data, sensitive details and credentials in my code.
- [x] My pull request represents one logical piece of work.
- [x] My commits are related to the pull request and look clean.
- [ ] I have added appropriate tests and documentation to any new ADF artifacts.
- [ ] I have updated the README file.

2023-12-04 07:56 UTC, nbanga01 commented
> hi @nbanga01 - your branch is out-of-date with the base branch. could you update it from main. Do a check with Akhil if in doubt. Do check with Akshay on the naming conventions to follow as well.

this is done!

2023-12-08 11:37 UTC, whow-kenvue-com requested changes
hi, pipeline/PIPE_hist_data_migration_redshift_snowflake_child is still having reference to SBX.. please remove if not required.

2023-12-08 11:37 UTC, whow-kenvue-com commented on pipeline/PIPE_hist_data_migration_redshift_snowflake_child.json
this is still referencing SBX.. if not required, please remove.

2023-12-08 11:42 UTC, nbanga01 commented on pipeline/PIPE_hist_data_migration_redshift_snowflake_child.json
yes, removed!

2023-12-08 12:06 UTC, whow-kenvue-com approved these changes
ok.

2023-12-08 12:28 UTC, awahi01 approved these changes
QA team tested the data and confirmed everything looks fine, approving the PR.

2023-12-08 12:38 UTC, SKuma016 commented
Approved

2023-12-08 12:40 UTC, SKuma016 approved these changes
Approved

2023-12-08 13:36 UTC, kkr01ken approved these changes
We have validated 330 tables and the data was matching

2023-12-08 14:31 UTC, Murali-MK commented
approved

2023-12-11 08:29 UTC, Murali-MK approved these changes
approved

2023-12-11 10:00 UTC, whow-kenvue-com approved these changes
enable auto-merge

2023-12-11 10:14 UTC, merged